server:
  port: 8203

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.200.128:8858
  zipkin:
    base-url: http://192.168.200.128:9411
    discovery-client-enabled: false
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.200.128:9200
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: java0509
    password: java0509
    virtual-host: /java0509
    listener:
      simple:
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 1000

